/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
//import User_DBConnection;
//import Admin.Admin_DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kunjf
 */
public class User_ProfilePage extends javax.swing.JFrame {

    /**
     * Creates new form User_ProfilePage
     */
    public User_ProfilePage() {
        
        
        initComponents();
        //getStudentDetails();
    }
    //to update student Details
    
    public boolean updateStudent(){
        boolean isUpdated = false;
        String studentId = txt_userID.getText();
        String studentName = txt_username.getText();
        String email = txt_email.getText();
        String contact = txt_contact.getText();
        String course = jCombo_coursename.getSelectedItem().toString();
        String branch = jCombo_branch.getSelectedItem().toString();
        
        try {
            Connection con = User_DBConnection.getConnection();
            String sql = "update users set Student_ID = ?, email = ?,contact = ? ,course = ? ,branch = ? where name = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, studentId);
            pst.setString(2, email);
            pst.setString(3, contact);
            pst.setString(4, course);
            pst.setString(5, branch);
            pst.setString(6, studentName);
            
            int rowCount = pst.executeUpdate();
            if(rowCount > 0)
            {
                isUpdated = true;
            }
            else
            {
                isUpdated = false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isUpdated;
    }
    public void getStudentDetails(){
        
        String username = txt_username.getText();
        try {
            Connection con = User_DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from users where name = ?");
            pst.setString(1, username);
            ResultSet rs = pst.executeQuery();
            
            {
            if(rs.next())
            {
                txt_userID.setText(rs.getString("Student_ID"));
                txt_contact.setText(rs.getString("contact"));
                txt_email.setText(rs.getString("email"));
                jCombo_coursename.setSelectedItem(rs.getString("course"));
                jCombo_branch.setSelectedItem(rs.getString("branch"));
            }
        }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_userID = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_email = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_contact = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCombo_coursename = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCombo_branch = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSMaterialButtonRectangle6 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 224, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_userID.setBackground(new java.awt.Color(204, 224, 255));
        txt_userID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_userID.setToolTipText("Enter UserID....");
        txt_userID.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_userID.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txt_userID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_userIDFocusLost(evt);
            }
        });
        txt_userID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userIDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 350, 40));

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel9.setText("User ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 120, 30));

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/gmail.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 50, 50));

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel11.setText("E-Mail:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 120, 30));

        txt_email.setBackground(new java.awt.Color(204, 224, 255));
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_email.setToolTipText("Enter E-Mail ID....");
        txt_email.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 350, 40));

        jLabel14.setBackground(java.awt.Color.white);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/phone.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 50, 50));

        jLabel15.setBackground(java.awt.Color.white);
        jLabel15.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel15.setText("Contact No:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 120, 30));

        txt_contact.setBackground(new java.awt.Color(204, 224, 255));
        txt_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_contact.setToolTipText("Enter Contact No....");
        txt_contact.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_contact.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txt_contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_contactFocusLost(evt);
            }
        });
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        jPanel1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 350, 40));

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/member.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 50, 50));

        txt_username.setBackground(new java.awt.Color(204, 224, 255));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_username.setToolTipText("Enter UserID....");
        txt_username.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_username.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 350, 40));

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel12.setText("Username:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 120, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/user.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel17.setText("Select Course:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 130, 30));

        jLabel13.setBackground(new java.awt.Color(102, 102, 255));
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/online-learning.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 50, -1));

        jCombo_coursename.setFont(new java.awt.Font("Book Antiqua", 0, 17)); // NOI18N
        jCombo_coursename.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech", "B.Sc", "M.Sc", "Ph.D" }));
        jCombo_coursename.setToolTipText("");
        jCombo_coursename.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCombo_coursename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCombo_coursenameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCombo_coursenameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCombo_coursenameMouseExited(evt);
            }
        });
        jPanel1.add(jCombo_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 350, 40));

        jLabel18.setBackground(new java.awt.Color(102, 102, 255));
        jLabel18.setForeground(new java.awt.Color(102, 102, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/branch.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 50, 50));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel19.setText("Select Branch:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 130, 30));

        jCombo_branch.setFont(new java.awt.Font("Book Antiqua", 0, 17)); // NOI18N
        jCombo_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ME", "CBE", "IT", "Microbiology", "Chemistry" }));
        jCombo_branch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCombo_branchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCombo_branchMouseExited(evt);
            }
        });
        jPanel1.add(jCombo_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 350, 40));

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel7.setText("USer Profile");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 40));

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/exit.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 50));

        rSMaterialButtonRectangle6.setBackground(new java.awt.Color(255, 102, 0));
        rSMaterialButtonRectangle6.setText("UPDATE");
        rSMaterialButtonRectangle6.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        rSMaterialButtonRectangle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 730));

        setSize(new java.awt.Dimension(520, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userIDFocusLost
        
    }//GEN-LAST:event_txt_userIDFocusLost

    private void txt_userIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userIDActionPerformed

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contactFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_contactFocusLost

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jCombo_coursenameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombo_coursenameMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jCombo_coursenameMouseClicked

    private void jCombo_coursenameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombo_coursenameMouseEntered
        // TODO add your handling code here:
        //jCombo_coursename.showPopup();
    }//GEN-LAST:event_jCombo_coursenameMouseEntered

    private void jCombo_coursenameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombo_coursenameMouseExited
        // TODO add your handling code here:
        //jCombo_coursename.hidePopup();
    }//GEN-LAST:event_jCombo_coursenameMouseExited

    private void jCombo_branchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombo_branchMouseEntered
        // TODO add your handling code here:
        //jCombo_branch.showPopup();
    }//GEN-LAST:event_jCombo_branchMouseEntered

    private void jCombo_branchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombo_branchMouseExited
        // TODO add your handling code here:
        //jCombo_branch.hidePopup();
    }//GEN-LAST:event_jCombo_branchMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
        User_ProfilePage page = new User_ProfilePage();
        dispose();
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void rSMaterialButtonRectangle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle6ActionPerformed
        // TODO add your handling code here:

        if(updateStudent()== true)
        {
            ImageIcon icon = new ImageIcon(User_ProfilePage.class.getResource("/test/checked.png"));
            JOptionPane.showMessageDialog(this, "<html><b style=\"font-family:Book Antiqua;font-size:14px;font-family:Book Antiqua;font-size:14px;color:green\">Student Profile Updated Successfully</b></html>","Message",JOptionPane.PLAIN_MESSAGE,icon);
            //cleartable();
            //setStudentDetailsToTable();
        }
        else
        {
            ImageIcon icon = new ImageIcon(User_ProfilePage.class.getResource("/test/error.png"));
            JOptionPane.showMessageDialog(this, "<html><b style=\"font-family:Book Antiqua;font-size:14px;font-family:Book Antiqua;font-size:14px;color:red\">Student Profile Updation Failed</b></html>","Message",JOptionPane.PLAIN_MESSAGE,icon);
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_ProfilePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> jCombo_branch;
    public static javax.swing.JComboBox<String> jCombo_coursename;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle6;
    private app.bolivia.swing.JCTextField txt_contact;
    private app.bolivia.swing.JCTextField txt_email;
    private app.bolivia.swing.JCTextField txt_userID;
    public static app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
